FROM golang:1.19.1-bullseye

RUN set -eux && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
     wget \
     make \
     unzip \
     git  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protoc-3.20.1-linux-x86_64.zip && \
    unzip -d /usr/local protoc-3.20.1-linux-x86_64.zip && \
    rm protoc-3.20.1-linux-x86_64.zip

WORKDIR /app/src

ENV GOBIN=/usr/local/bin/
RUN go install github.com/cosmtrek/air@v1.40.4 && \
    go install golang.org/x/tools/cmd/goimports@v0.2.0 && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.14.0 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.10.3 && \
    go install github.com/google/wire/cmd/wire@v0.5.0 && \
    go install github.com/volatiletech/sqlboiler/v4@v4.13.0 && \
    go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@v4.13.0

CMD ["air", "-c", "/app/src/.air.toml"]