FROM golang:1.19.1-alpine

RUN set -eux && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN apk upgrade --update && \
    apk add build-base protobuf-dev
    
WORKDIR /app/src

ENV GOBIN=/usr/local/bin/
RUN go install github.com/cosmtrek/air@v1.40.4 && \
    go install golang.org/x/tools/cmd/goimports@v0.2.0 && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.14.0 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.10.3 && \
    go install github.com/google/wire/cmd/wire@v0.5.0 && \
    go install github.com/volatiletech/sqlboiler/v4@v4.13.0 && \
    go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@v4.13.0

CMD ["air", "-c", "/app/src/.air.toml"]